# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Zip up the app
          command: |
            mkdir ~/target
            zip -r ~/target/ndelius-wrapper.zip .
      - persist_to_workspace:
            root: ~/target/
            paths:
              - ./ndelius-wrapper.zip
      - store_artifacts:
            path: ~/target
            destination: zips

  deploy:
    docker:
      - image: paulodiovani/aws-eb-cli
    working_directory: ~/repo
    steps:
    - attach_workspace:
        at: /workspace
    - checkout
    - run:
        name: Deploy to Elastic Beanstalk
        command: |
            eb deploy --label $CIRCLE_BUILD_NUM
    - run:
        name: Deploy to Elastic Smoketest Beanstalk
        command: |
            eb deploy delius-wrapper-smoke-test --label $CIRCLE_BUILD_NUM

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                      only: master
